config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root to: 'topics#index'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :topics do
    resources :comments
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  default_scope -> { order(created_at: :asc) }
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true, length: { minimum: 10, maximum: 150 }, uniqueness: { case_sensitive: false }
  validates :content, presence: true, length: { minimum: 20 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(updated_at: :desc, created_at: :desc) }

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("lower(title) LIKE lower(?)", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }

  has_many :comments, dependent: :destroy
  has_many :topics, dependent: :destroy

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
   self.remember_token = User.new_token
   update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
   update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   # before_action :logged_in_user, only: [:create, :destroy]

  def create

    if logged_in?
      @topic = Topic.find(params[:topic_id])
      @comment = @topic.comments.create(comment_params)
      @comment.user_id = current_user.id

      if @comment.save
        redirect_to topic_path(@topic)
      else
        flash.now[:danger] = 'You should be logged to comment!'
        render "sessions/new"
      end
    else
      flash.now[:danger] = 'You should be logged to comment!'
      render "sessions/new"
    end

  end

  def destroy
  end

  private

    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
      end
    end

    def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @topic = current_user.topics.build
  end

  def edit
  end

  def create
    @topic = current_user.topics.build(topic_params)

      if @topic.save
        redirect_to @topic, notice: 'Topic was successfully created.'
      else
        render :new
    end
  end

  def update
      if @topic.update(topic_params)
        redirect_to @topic, notice: 'Topic was successfully updated.'
      else
        render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to root_path, notice: 'Topic was successfully deleted.'
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Vanhack Awesome Forum!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when "success" then "ui green message"
      when "error" then "ui red message"
      when "danger" then "ui red message"
      when "notice" then "ui blue message"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
      session[:user_id] = user.id
  end

  def remember(user)
   user.remember
   cookies.permanent.signed[:user_id] = user.id
   cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
   user == current_user
 end

 def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "ui tiny left floated circular image")
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p><%= @comment.comment %> </p>
</div>

app/views/comments/_form.html.erb
<div class="ui form">
    <%= form_with(model: [@topic, @topic.comments.build], local: true) do |f| %>
      <div class="field">
        <%= f.label :comment %>
        <%= f.text_area :comment %>
      </div>
      <div class="actions">
        <%= f.submit "Reply", class: "ui tiny primary button" %>
      </div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="ui footer">
  <p> Just a simple footer... </p>
</div>

app/views/layouts/_header.html.erb
<div class="ui secondary menu forumMenu">
  <%= link_to root_path, class: "ui image" do %>
    <%= image_tag("vanhack-logo") %>
  <% end %>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <%= form_tag(topics_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Topics" %>
          <%= button_tag(type: "submit", class: "ui gray basic button") do %><i class="search link icon"></i><% end %>
        <% end %>

      </div>
    </div>

    <% if logged_in? %>
      <div class="ui simple dropdown item">
          <div class="ui mini image"><%= gravatar_for current_user %></div>
          <i class="dropdown icon"></i>
          <div class="menu">
            <div class="item">
              <%= link_to "View Profile", current_user, class:"ui primary button" %>
            </div>
            <div class="item">
              <%= link_to "Edit Profile", edit_user_path(current_user), class:"ui primary button" %>
            </div>
          </div>
      </div>
      <div class="item">
        <%= link_to "Log out", logout_path, class:"ui secondary button" , method: :delete %>
      </div>
    <% else %>
    <div class="item">
      <%= link_to "Log in", login_path, class: "ui primary button" %>
    </div>
    <div class="item">
      <%= link_to "Sign Up", signup_path, class: "ui primary button" %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vanhack Awesome Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
  <%= render "layouts/header" %>
	<div class="ui container">

    <% flash.each do |message_type, message| %>
        <div class="<%= flash_class(message_type) %> closable">
          <i class="close icon"></i>
          <%= message %>
        </div>
      <% end %>

		<%= yield %>
	</div>
  <!-- <div class="debugBox">
    <%= debug(params) if Rails.env.development? %>
  </div>
  <%= render "layouts/footer" %> -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul class="list">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/topics/_form.html.erb
<div class="ui form">
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation" class="ui red message">
      <i class="close icon"></i>
      <div class="header">
        <%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:
      </div>

      <ul class="list">
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :topic_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :topic_content %>
  </div>

  <div class="actions">
    <%= form.submit "Save Topic", class: "ui primary button" %>
  </div>
<% end %>
</div>

app/views/topics/edit.html.erb
  <div class="header">Editing Topic</div>
  <div class="upButtons">
    <%= link_to 'Show', @topic, class: "ui tiny green button" %>
    <%= link_to 'Back', topics_path, class: "ui tiny gray button" %>
  </div>


<%= render 'form', topic: @topic %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>
<% if logged_in? %>
  <%= link_to 'New Topic', new_topic_path, class: "ui tiny primary button" %>
<% end %>

<table class="ui striped table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.title, topic %></td>
        <td><%= topic.comments.count %></td>
        <% if logged_in? && current_user.id == topic.user_id %>
          <td>
              <%= link_to edit_topic_path(topic) do %>
                <i class="edit icon"></i>
              <% end %>
          </td>
          <td>
              <%= link_to topic_path(topic), method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="trash icon"></i>
              <% end %>
          </td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr><th colspan="4">
      <div class="ui right floated pagination menu">
            <%= will_paginate @topics, class: "digg_pagination" %>
      </div>
    </th>
  </tr></tfoot>
</table>

app/views/topics/new.html.erb
<div class="header">New Topic</div>
<div class="upButtons"><%= link_to 'Back', topics_path, class: "ui tiny gray button" %></div>

<%= render 'form', topic: @topic %>

app/views/topics/show.html.erb
<div>
  <div>
    <% if logged_in? && current_user.id == @topic.user_id %>
      <%= link_to 'Edit', edit_topic_path(@topic), class: "ui small primary button" %>
    <% end %>
    <%= link_to 'Back', topics_path, class: "ui small gray button" %>
  </div>
  <hr>
  <div class="topic_header"><%= @topic.title %></div>

  <div class="topic_content">
    <%= simple_format(@topic.content) %>
  </div>
  <hr />
</div>
<div>
  <h2>There are <%= @topic.comments.count %> comments on this Topic. </h2>
  <% @topic.comments.each do |comment| %>
    <div class="boxComment">
      <div>
        <%= gravatar_for comment.user %>
      </div>
        <div class="commentHeader">
          <span><%= comment.user.name %></span> <span class="ui gray tag label"><%= comment.created_at.strftime("%d/%m/%Y at %H:%M:%S") %></span>
        </div>
        <div><%= comment.comment %></div>
    </div>
  <% end %>
  <%= render "comments/form"  %>
  <br />
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="ui form">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
      </div>

      <%= f.submit "Save changes", class: "ui primary button" %>
    <% end %>
    <hr />
    <div class="gravatar_edit">
      <%= gravatar_for @user %> <br />
      <a href="http://gravatar.com/emails" target="_blank" class="ui tiny gray button">change</a>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="ui form">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
      </div>

      <div class="actions">
        <%= f.submit "Create my account", class: "ui primary button" %>
      </div>
    <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
  <br />
</h1>
<p class="ui blue tag label"><%= @user.email %></p>